version: "3.9"
services:
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=naff_db
    ports:
      - 5432:5432
    volumes:
      - naff-db:/var/lib/postgresql/data
volumes:
  naff-db: