version: "3.9"
services:
  database:
    image: surrealdb/surrealdb:latest
    ports:
      - "8000:8000"
    command: "start --pass Yeet file:///db"
    volumes:
      - naff-db:/db

volumes:
  naff-db: